### ISSUE TITLE
没有办法自启动

### ISSUE THREAD

**Issue by duzhen1996** [zhaokeli/FastGestures#10]
华为matebook pro x，自启动失败，win10。

并且重启之后软件就没法打开了。

**Comment by zhaokeli** [comment]
尝试把安全软件关闭试下，如果还不行。 可查看下  电脑->管理->事件查看器->windows 日志->应用程序中是否有此软件的错误描述

**Comment by duzhen1996** [comment]
你好，我又尝试了一下，我发现这个软件没有办法启动第二次。只有第一次安装的时候启动一下是可以的

**Comment by duzhen1996** [comment]
我查到错误了，事件ID 1000， 任务类别（100），关键字 经典，用户 暂缺，异常代码0xc0000409

**Comment by zhaokeli** [comment]
最新版本已经修复这个问题
