### ISSUE TITLE
误启动截屏功能

### ISSUE THREAD

**Issue by codychen98** [zhaokeli/FastGestures#11]
我只需要三指移动窗口的功能 可是使用过程中经常启用截屏功能,请问如何关闭截屏功能 也不影响 三指移动窗口的使用 谢谢

**Comment by 735579768** [comment]
关闭下图开关
![image](https://user-images.githubusercontent.com/2497797/185819601-7b6bc50d-b22c-474e-a960-993ca4a94e78.png)

**Comment by codychen98** [comment]
<img width="620" alt="Screenshot_1" src="https://user-images.githubusercontent.com/107047989/185820445-60e69af1-371d-43bc-ba82-5dec7f8690d6.png">

**Comment by codychen98** [comment]
这样后就无法使用三指移动了

**Comment by 735579768** [comment]
额你触控开关全关了。自然用不了。 建议到官网查看下使用入门

**Comment by codychen98** [comment]
还是不行,我其他全开了 只要多指点击是关的 三指移动就用不了, 试过卸载重装 用原厂设置也是,只要一关多指点击就不行. 上一个版本也不行

**Comment by zhaokeli** [comment]
软件卸载，最后有个提示，删除配置信息，然后重装， 打开设置->三指设置->仅保留三指拖动功能
![image](https://user-images.githubusercontent.com/2497841/185931780-a4093638-f3b6-47fd-bf38-67d83c29d807.png)

**Comment by codychen98** [comment]
还是一样... 可能我跟这软件无缘吧, 还是谢了
