### ISSUE TITLE
扩展屏幕180度旋转的情况下，三指拖移的功能不正常

### ISSUE THREAD

**Issue by LiukDiihMieu** [zhaokeli/FastGestures#12]
情况：Windows 11下笔记本连接了扩展屏幕，由于扩展屏幕是颠倒放置的，在Windows的设置中设置了旋转180度。该情况下，三指拖移时上下是颠倒的。（单指在触控板上操作时方向没有问题。）

望确认，多谢！

**Comment by zhaokeli** [comment]
2.1.20版本已经修复这个问题，确认下自己使用的版本
