### ISSUE TITLE
三指手势触发逻辑的优化

### ISSUE THREAD

**Issue by 91he** [zhaokeli/FastGestures#13]
现象：三指拖动时，手指有时不能同时落在触摸板上，会导致三指手势无法正常触发，正常使用时大约有20%~30%的几率会如此。
复现逻辑：二指先落到触摸板上，第三指稍后落，继续拖动则三指拖动无法触发，在选择文字或慢速拖动的时候更容易触发。

**Comment by zhaokeli** [comment]
方便的话,麻烦留下你使用的系统，软件版本，笔记本型号。

**Comment by 91he** [comment]
> 方便的话,麻烦留下你使用的系统，软件版本，笔记本型号。

型号：Surface laptop go 2
版本：2.1.21

**Comment by 91he** [comment]
@zhaokeli 有一个常用的场景我补充下，当准备在页面上选取文字时，单指移动光标，到达位置后加入另外两指进行三指选中，这时是选中不了的，必须松开手指并重新进行三指拖动，这样选中的逻辑就会很别扭。

**Comment by 91he** [comment]
@zhaokeli 另外，在微信截图、飞书截图、Win+Shift+S截图时，都无法进行三指拖动，这个功能能增加下吗？

**Comment by zhaokeli** [comment]
> @zhaokeli 另外，在微信截图、飞书截图、Win+Shift+S截图时，都无法进行三指拖动，这个功能能增加下吗？

可以尝试关闭此开关试试，
![image](https://user-images.githubusercontent.com/2497841/192766290-84336112-0777-4b7b-8edc-a3d8daa5c690.png)

**Comment by zhaokeli** [comment]
> @zhaokeli 有一个常用的场景我补充下，当准备在页面上选取文字时，单指移动光标，到达位置后加入另外两指进行三指选中，这时是选中不了的，必须松开手指并重新进行三指拖动，这样选中的逻辑就会很别扭。

下个版本中会优化。

**Comment by 91he** [comment]
> > @zhaokeli 有一个常用的场景我补充下，当准备在页面上选取文字时，单指移动光标，到达位置后加入另外两指进行三指选中，这时是选中不了的，必须松开手指并重新进行三指拖动，这样选中的逻辑就会很别扭。
> 
> 下个版本中会优化。

非常感谢，新版已经没有问题了，Alipay小小支持了一波。
