### ISSUE TITLE
快速、多次 ctrl+space 切换输入法的情况下，插件奔溃退出

### ISSUE THREAD

**Issue by BBaiYuChen** [zhaokeli/FastGestures#14]
开启插件，开启三指拖拽，用 ctrl+space 快速、多次切换输入法，程序后台会自己退出，感觉是触发了啥不清楚的冲突，导致异常奔溃掉了，可以尝试一下这个 case。输入法的切换是个挺频繁的场景，这个 case 的触发概率应该还是很高的。

**Comment by zhaokeli** [comment]
用的是最新版本吗？开启什么插件？ 崩溃时没有提示提交崩溃日志吗？ 这边没收到相关崩溃日志

**Comment by zhaokeli** [comment]
> 开启插件，开启三指拖拽，用 ctrl+space 快速、多次切换输入法，程序后台会自己退出，感觉是触发了啥不清楚的冲突，导致异常奔溃掉了，可以尝试一下这个 case。输入法的切换是个挺频繁的场景，这个 case 的触发概率应该还是很高的。

2.1.24 已修复
