### ISSUE TITLE
请问本软件有触摸板手势功能吗

### ISSUE THREAD

**Issue by lithiumleeow** [zhaokeli/FastGestures#15]
我使用的是apple 妙控板2 
看到软件功能描述好像是支持触控板手势的，但是添加手势时用触控板没反应
不知道这款软件能否实现像gesturesign一样的体验
类似于macos上的better than better一样的功能
实在是非常眼馋这个三指拖拽

**Comment by zhaokeli** [comment]
支持触控板，使用方法可以查看使用文档

触控板手势
触控手势需要先按下键盘上设置的手势键，然后可执行以下操作

1、四个角落点击事件
2、四个边(中间)点击事件
3、四个边左右，上下滑动连续触发事件
4、3，4指，在触控板上短按、长按事件
5、正常在触控板中间1，2，3，4画手势方向触发指定操作
