### ISSUE TITLE
有办法支持在 RDP 远程的时候使用吗？

### ISSUE THREAD

**Issue by lancelot-lewis** [zhaokeli/FastGestures#16]
背景是：
通过一台笔记本电脑，远程了一台台式机

**Comment by zhaokeli** [comment]
在远程的台式机中同样安装软件，是可以直接使用的，遇到了什么问题，可以详细描述下
![image](https://user-images.githubusercontent.com/2497841/227783786-766d9b5e-e603-4b00-b870-932bb3da9ab7.png)

**Comment by lancelot-lewis** [comment]
安装后，三指拖移没反应

**Comment by zhaokeli** [comment]
> 安装后，三指拖移没反应

三指拖移是你本机笔记本上的功能，当你笔记本远程台式机时，软件不在远程桌面这个应用界面上使用手势,  所以三指拖动无效。 把下面勾去掉就可以了。但远程台式机上的手势可能就不能用了。
![image](https://user-images.githubusercontent.com/2497841/227832141-ff788999-6ac8-4461-b963-2319ac85bd4b.png)

**Comment by lancelot-lewis** [comment]
> 但远程台式机上的手势可能就不能用了。

台式机中本来就没有手势可以用

---

排除应用后，可以了，很强 👍
