### ISSUE TITLE
关闭”仅在主屏触发“这个选项，不起作用，副屏仍然无法使用触控板事件

### ISSUE THREAD

**Issue by zzrice** [zhaokeli/FastGestures#17]
作者您好，我是双屏用户，在2.1.31版本中，关于屏幕/触控板这个页面设置里，我关闭了”仅在主屏触发这个选项”，但是当想对副屏的窗口使用触控板事件时，无法执行。在主屏幕则没有问题，所以特来询问一下，是不是“仅在主屏触发“这个选项没有生效。
![Snipaste_2023-04-06_16-53-22](https://user-images.githubusercontent.com/107989923/230326671-7d4b1b11-8a0e-481b-aeca-bf20ab052b60.png)
![Snipaste_2023-04-06_16-47-30](https://user-images.githubusercontent.com/107989923/230326680-70165a47-d85d-4fcd-b3fd-2de3e917e1cb.png)

**Comment by zhaokeli** [comment]
2.1.32 已经解决此问题
