### ISSUE TITLE
祝贺1.0发布🎉！第一时间体验，反馈下当前问题及一点建议~~~

### ISSUE THREAD

**Issue by o000u** [zhaokeli/FastGestures#2]
首先，非常感谢作者的辛苦付出，毕竟都是抽自己的业余时间在做，真的很不容易，替广大机友们说声谢谢！
下面是目前1.0初步浅体验下来的一些问题及建议：

问题——

主程序：
1、鼠标下窗口的选项关闭没作用——关闭后，手势仍然是作用于鼠标下面的窗口，而不是当前激活的前台窗口
2、名称OSD显示的UI圆角不够平滑，比较粗糙
3、定义执行操作时，上下左右箭头键会识别成num8/2/4/6

触控板模块：
1、多指单点自定不起作用，均会激活开始菜单
2、触控板手势识别过于敏感，容错率低，导致识别率低
3、TipTap连续多次执行时会时不时卡住——即【三指，左/中/右指轻点】时

建议——

主程序：
1、名称显示在手势结束后的显示时间建议长些——不然看不清激活的是什么手势
2、名称显示支持独立设置单个动作是否显示—— 像复制、剪切、粘贴这种手势显示会比较方便，但如果每个手势都显示会觉得比较打扰，所以只设一个全关或全开的按钮感觉不够
3、自定义退出热键——因为与其它软件有冲突，每次启动都会提示热键注册失败

鼠标模块：
1、各个按键手势分开——目前是所有手势键都是执行同一套动作，如果能根据不同手势键执行不同动作，比如右键上划与中键上划可分开设置，互不关联，功能上会得到大大丰富！可能作者初衷是想减少记忆成本，可以理解，但那样的话太浪费其它的鼠标键了，可以考虑加个开关
2、组合按键按下马上执行，而不是松开——目前FG（FastGestures）支持鼠标按键组合，比如按住右键同时再点左键执行动作，但都是在松开左键才执行，如果能在按下左键时马上执行会更舒服些，不会给人滞后感
3、单个鼠标按键定义——比如自定义中键、X1、X2等键的单击执行动作

触控板模块：
1、TipTap拓展——很高兴看到FG目前支持【三指，左/中/右指轻点】等动作，就是俗称的TipTap，但感觉不够，如果能增加【二指，左/右指轻点】、【四指，左/右指轻点】等动作会更加方便
2、点击与轻点分开——目前按下去与轻点是不区分的，如果能区分开就可以分别定义【三指轻点】、【三指点击】等手势动作，在Mac下这样用习惯了，感觉回不去了，哈哈

暂时就这些，体验得有点匆忙，毕竟看到1.0出来后，第一时间就下下来测试了，心情比较激动，然后又迫不及待想让FG变得更完善，所以就写得有点仓促，仅供参考哈，望见谅~~~

最后，再次感谢作者，老大辛苦了！

对了，补上测试设备：
台式机
苹果妙控板2
Windows 11 (22000.100)

**Comment by zhaokeli** [comment]
1、鼠标下窗口的选项关闭没作用, 试过了正常，可描述下具体什么场景，在什么程序上操作时不管用
2、圆角问题，dpi 高分屏显示等ui问题，放后期逐步优化，前期以功能为准
3、上下左右箭头键会识别成num8/2/4/6，这个应该不影响，显示是几这个键但实际不是这几个数字，还是上下左右方向键码，如果录入快捷键后执行结果不正确，可反馈下键盘布局图片。
4、多指短按和长按试过了也是正常的，使用时注意看下上面的时间滑块限制。
4、组合键：按下左中右键后可以划手势方向，也可按左中右键(多次点击)，因为可无限点击所以没有加按下后就执行某个操作。
6、触控板关于轻点和点击，因为windows目前没有找到实现这种功能的api，所以没有完全实现，只能尽量模仿完善
最后：
关于手势识别和触控板精度。确实还有很大优化空间, 一直在寻找更好的解决方案
热键等已经记录在案。会在下个版本中给出设置
