### ISSUE TITLE
系统截屏时三指拖拽不生效

### ISSUE THREAD

**Issue by Raydon10** [zhaokeli/FastGestures#20]
如题

**Comment by zhaokeli** [comment]
> 如题

是win11   win+shift+s 截图吗？  2.1.33 版本会优化

**Comment by Raydon10** [comment]
> > 如题
> 
> 是win11 win+shift+s 截图吗？ 2.1.33 版本会优化

是的，期待。同时也请考虑更多的三指拖拽场景适配，我主要用这个～
