### ISSUE TITLE
希望能实现三指查词

### ISSUE THREAD

**Issue by jueljust** [zhaokeli/FastGestures#21]
mac上三指轻拍等于调用词典查当前词 不知道是不是能实现 词典可以是欧路之类支持离线的词典 有道最新版本好像不能离线查词了

**Comment by zhaokeli** [comment]
本款软件只是支持手势执行对应的操作，具体功能实现要借助其它工具，支持3指点击触控板执行指定操作， 但查词这个操作需要自行实现
