### ISSUE TITLE
管理员模式下的PowerToys鼠标跳转工具的窗口有时会出现在当前窗口下层

### ISSUE THREAD

**Issue by gdnre** [zhaokeli/FastGestures#23]
PowerToys以管理员模式运行后，使用fastgestures发送快捷键来执行鼠标跳转工具的快捷键(win+shift+d)，出现的跳转窗口有时会在鼠标当前位置窗口的下层，而且正常情况下点击屏幕其它地方，鼠标跳转窗口会自动关闭，这种情况下必须在跳转窗口内点击才能关闭。
使用鼠标在桌面以及跳转窗口上多次执行手势时，会比较容易触发该情况。

我尝试过使用fastgestures的管理员和非管理员模式运行，以及鼠下窗口的选项，都无法解决问题，但如果PowerToys不以管理员模式运行或是用键盘按下快捷键就不会出现上述问题。用wgestures也没有出现过这样的问题，因此想问问fastgestures的快捷键和直接按键盘快捷键是否有什么不同？

另外，焦点在任务管理器时，我无法使用手势，根据常见问题安装了证书也不行，不确定这是否和上述问题有关联。

**Comment by gdnre** [comment]
我通过直接打开鼠标跳转工具的exe文件解决了这个问题，证书也安好了，但还是很好奇这个快捷键为什么会出bug。

**Comment by zhaokeli** [comment]
先确保你用的是最新版本。 
使用FastGestures的哪种操作来发送的快捷键。 屏幕触发角事件。还是手势键画手势后执行的？

**Comment by gdnre** [comment]
> 先确保你用的是最新版本。 使用FastGestures的哪种操作来发送的快捷键。 屏幕触发角事件。还是手势键画手势后执行的？
使用的最新版本。（问题提出时用的2.1.38，刚刚重新试了下2.1.39也是这样）
是用手势键画手势后执行的，我将手势设置为了"右键↓"。

**Comment by gdnre** [comment]
> 先确保你用的是最新版本。 使用FastGestures的哪种操作来发送的快捷键。 屏幕触发角事件。还是手势键画手势后执行的？
使用的最新版本。（问题提出时用的2.1.38，刚刚重新试了下2.1.39也是这样）
是用手势键画手势后执行的，我将手势设置为了"右键↓"。

**Comment by gdnre** [comment]
使用的最新版本。（问题提出时用的2.1.38，刚刚重新试了下2.1.39也是这样）
是用手势键画手势后执行的，我将手势设置为了"右键↓"。

**Comment by zhaokeli** [comment]
"出现的跳转窗口有时会在鼠标当前位置窗口的下层" ,  这句话意思是执行完后，出现的跳转窗口上面有一个窗口(这个窗口就像置顶了)？

查看下你手势操作设置中有没有勾选
![image](https://github.com/zhaokeli/FastGestures/assets/2497841/fd90974a-d498-4a68-8e3e-59265bdf52dc)
，去掉后试试。


如果还有问题，方便的话录个动图或视频看下。

**Comment by gdnre** [comment]
“是否先激活鼠标下的窗口”选项不论是否勾选都是类似的表现。

下面是正常情况（用键盘按快捷键、用手势打开这个应用程序的情况），不管怎么跳转窗口都像是置顶显示的：
![正常](https://github.com/zhaokeli/FastGestures/assets/94197241/499a1ae8-e349-482c-9ebf-ab6e987132f7)

下面是使用手势发送快捷键打开这个跳转窗口的情况，没有勾选上面说的选项，就像是始终在当前活动窗口下层显示：
![手势不勾选](https://github.com/zhaokeli/FastGestures/assets/94197241/6143393f-6294-47bc-905f-8114a0963292)

**Comment by zhaokeli** [comment]
![动画2](https://github.com/zhaokeli/FastGestures/assets/2497841/4159ec9a-f86c-40a0-8630-5762411e3a09)

![image](https://github.com/zhaokeli/FastGestures/assets/2497841/9b348c98-e19c-4614-aa63-2491acb5fd35)

![image](https://github.com/zhaokeli/FastGestures/assets/2497841/6f2b10b7-fc99-41c4-9928-51b081702ee6)

可以的话把你的配置导出来一份发我邮箱 735579768@qq.com。我这边38  39版本都试了。  都没出现你的那种情况

另外再确定下，你那边是所有应用都这样。还是只是你演示的这两个应用会这样。

**Comment by gdnre** [comment]
好的，配置发你了。
是所有应用都这样，另外刚刚发现我这边powertoys窗口打开时(最小化也可以，只要不是只显示在托盘图标时)，用手势执行这个操作就是正常的。
