### ISSUE TITLE
[FR] 当一个窗口置顶时, 在这个置顶的窗口上显示鼠标手势

### ISSUE THREAD

**Issue by doit132** [zhaokeli/FastGestures#24]
当一个窗口置顶时, 在这个置顶的窗口上鼠标手势不可见, 如下图动画所示, 最上面的是一个vscode置顶窗口

![动画](https://github.com/zhaokeli/FastGestures/assets/117004316/03e0a0be-b6da-475b-91ae-93f75e63bb39)

- 使用环境
    - FastGesture 64 位压缩包
    - 版本 Windows 11 专业版
    - 版本 23H2

**Comment by zhaokeli** [comment]
2.1.41 已解决这个问题
