### ISSUE TITLE
2.1.41版本在随系统启动后会弹出程序主界面

### ISSUE THREAD

**Issue by TscCai** [zhaokeli/FastGestures#25]
我记得之前使用时程序都是静默启动，只在托盘上留一个图标。请问是哪里没设置正确吗？

**Comment by zhaokeli** [comment]
![image](https://github.com/zhaokeli/FastGestures/assets/2497841/447da8ef-e05a-4e32-a80f-bda8539aa215)
如果不是以管理员权限启动的话，就开启管理员权限,会提示软件重启。
然后把上面开机后启动设置开关,关下然后再开(确保清理掉有问题的启动项)


最后不想以管理员权限启动的话可以关掉




另外麻烦发下这个信息，我查下什么原因导致的启动项显示了界面。 可以去掉里面的一些关键路径信息
![image](https://github.com/zhaokeli/FastGestures/assets/2497841/94cd07fb-2f6c-4b2d-8715-f81a266ca4a5)

**Comment by zhaokeli** [comment]
下载2.1.42以上  重新覆盖安装即可

**Comment by TscCai** [comment]
> ![image](https://user-images.githubusercontent.com/2497841/282017278-447da8ef-e05a-4e32-a80f-bda8539aa215.png) 如果不是以管理员权限启动的话，就开启管理员权限,会提示软件重启。 然后把上面开机后启动设置开关,关下然后再开(确保清理掉有问题的启动项)
> 
> 最后不想以管理员权限启动的话可以关掉
> 
> 另外麻烦发下这个信息，我查下什么原因导致的启动项显示了界面。 可以去掉里面的一些关键路径信息 ![image](https://user-images.githubusercontent.com/2497841/282018272-94cd07fb-2f6c-4b2d-8715-f81a266ca4a5.png)

感谢！我已按照所提供的方法解决了开机显示软件界面。调试信息如下
FastGestures 2.1.41 x64 Install
OSVersion: 25
OSName: Windows 11 Enterprise 23H2 22631.2715 (64-bit)
NTVersion: 6.3
Path: C:\Program Files\FastGestures
DataPath: C:\Users\xxx\AppData\Roaming\zhaokeli.com\FastGestures
Screen: size:2880x1800 scale:1440x900 dpi:2.00
TouchPad: 11700x7200
TouchScreen: 0x0
IsAsAdmin: 0
IsBook: 1
TouchSpeed: 0
OnlyThree: 1
