### ISSUE TITLE
运行后1分钟出现CPU及内存飙升

### ISSUE THREAD

**Issue by tinpont** [zhaokeli/FastGestures#26]
![微信截图_20240113211345](https://github.com/zhaokeli/FastGestures/assets/3940642/b27daeab-1ba8-49e0-af1f-1ce17e301a2c)

版本	Windows 11 家庭中文版
版本	22H2
安装日期	‎2024/‎1/‎3
操作系统版本	22621.3007
体验	Windows Feature Experience Pack 1000.22681.1000.0

安装后即出现，初步预估是GUI展示时，由于版本兼容问题，出现死循环创建对象

**Comment by zhaokeli** [comment]
显示的cpu占用可能是，由FastGestures启动的其它程序，  在资源管理器中显示为FastGestures的子进程。所以才归类到FastGestures下了。  实际并非是FastGestures占用的cpu
