### ISSUE TITLE
非常實用的更新！提兩個 2.2.13 以來遇到的問題

### ISSUE THREAD

**Issue by ClixTW** [zhaokeli/FastGestures#30]
## 運行環境
Windows 11 23H2，軟體版本 2.2.14 x64
手勢鍵自動作為第一個手勢符：開
需要其他資訊的話，再麻煩告知我補充。

### 狀況描述
上次更新允許側鍵直接觸發單點手勢，但實際用發現一個問題不知是否有意為之？
單擊側鍵除了觸發手勢，依然會送出側鍵本來的鍵值。
比如設定在瀏覽器內單擊 X1 即送出 P 鍵，按下後除了會送出 P 鍵外，還會回到上一頁（X1 本來的鍵值），
無論全局還是個別應用都會發生，沒辦法完全覆寫側鍵的功能。

![image](https://github.com/zhaokeli/FastGestures/assets/4404305/4b6f95c7-f9e9-4531-9fe5-67bf18ca0793)
### 預期結果
設定單擊側鍵的手勢後，完全取代側鍵的功能，不要觸發側鍵原本的鍵值。

### 狀況描述
設置 / 快捷鍵 / OCR識別，設定快捷鍵後按下清除沒有效果，導致無法清除快捷鍵。

![image](https://github.com/zhaokeli/FastGestures/assets/4404305/b3996d34-7ab5-4389-a26d-3aa2dd54ce8e)
### 預期結果
按下清除後，快捷鍵會被刪除並顯示無。

## 後話
最後提個想法，希望送出快捷鍵和發送快捷鍵組的部分，能夠支援滑鼠鍵值，
比如我設定了右鍵按下左滑 / 右滑是 Alt + ← / → 來模擬側鍵的前進後退，
但在某些軟體上和 X1 / X2 真正的前進後退行為不一樣（比如 YouTube 畫面，Alt + ← / → 會變成調整時間軸）
如果能直接把手勢設定成送出 X1 / X2 就太棒了😄

長期用了 WGestures 1 & 2、MouseGestureL.ahk、StrokesPlus.net，
您的 FastGesture 在功能性和易用性達到了最好的平衡，更具備了獨創又實用的功能，
真的非常感謝您開發了這個偉大的軟體🙏

**Comment by zhaokeli** [comment]
![QQ_1720580215577](https://github.com/zhaokeli/FastGestures/assets/2497841/b6a370a2-b64f-4c76-b858-c7ee6aefa6cd)
这个清除的问题。确实是bug. 会在2.2.16版本修复

侧键(x1,x2)设置手势后， 不影响原有消息值触发。是有意为之。 如果想拦截原有键值可勾选x1 x2为手势启动键
![QQ_1720580462392](https://github.com/zhaokeli/FastGestures/assets/2497841/5087e27d-ccf0-4c81-bc14-e7bebff01d88)

![QQ_1720580529961](https://github.com/zhaokeli/FastGestures/assets/2497841/ddf65b17-a581-4272-8c48-13b4e2ef27f8)
这一部分现有功能是可以实现的。 可以使用lua脚本。提供的有滑鼠对应的操作函数

**Comment by ClixTW** [comment]
感謝繁忙中撥空說明，我再來研究一下！
