### ISSUE TITLE
打字的时候碰到触摸板会导致键盘短时间没有响应

### ISSUE THREAD

**Issue by StarDuster** [zhaokeli/FastGestures#4]
感觉这个问题有点诡异，具体复现方式是用比较大面积（比如大拇指根部）碰一下触摸板，此时键盘输入就会无响应。
Windows自带的精确触摸板三指操作都是关闭的。
我只启用了三指拖动，手势全都关闭了，已经确认过fastgestures退出的时候没有这个问题，这是和我其他软件冲突还是确实有这个问题？
是否存在debuglog看看这个操作触发了什么？

Thinkpad X13, Windows 10 21h1

**Comment by zhaokeli** [comment]
2.1.3 (及)以上版本已经优化

**Comment by StarDuster** [comment]
nice!
