### ISSUE TITLE
单指从外进入触控板时鼠标不动

### ISSUE THREAD

**Issue by starskyzheng** [zhaokeli/FastGestures#5]
使用的为2.1.5版本。
打开触控手势之后，单指从触控板外进入触控板之后，无论如何移动手指，屏幕上的光标均不移动。
而如果从四个角进入则可以正常移动光标。
第二个选项卡“屏幕/触控板”无论如何设置都没效果。
关闭“触控手势”或关闭FastGestures后，恢复正常。

**Comment by StarSkyZheng** [comment]
补充一下：如果以非常快的速度从边缘的中间进入触控板，也正常移动光标
不太清楚原因，是我配置的问题还是Bug?
