### ISSUE TITLE
windows 11系统中, 录入手势没有反应, 录入不了

### ISSUE THREAD

**Issue by netjune** [zhaokeli/FastGestures#6]
"请在屏幕或触控板上画出手势, 监控中..."

在触控板上画了没有一点效果, 监控不到.

另外, 预置的手势也没有效果, 目前仅仅三指拖动有效.

普通用户权限运行, 杀毒软件是联想管家自带的.

**Comment by zhaokeli** [comment]
先确认软件是最新版本。鼠标手势是否可用，正常用手指画手势时屏幕上是否有轨迹显示，
最后把设置界面截图贴出来看下

**Comment by netjune** [comment]
软件是2.1.7, 三指拖动可以使用, 四指拖动屏幕上能看到轨迹显示. 

双指拖动就没有轨迹显示, 拖动也没有效果.

录入手势界面, 无法录入手势.

设置界面: https://github.com/netjune/temp_files/blob/master/fast_guesture-setting.png

手势配置界面: https://github.com/netjune/temp_files/blob/master/fast_guesture-app.png

**Comment by 735579768** [comment]
> 

先升级到最新版本，看上面问题解决了没，另外双指移动需要分开一段距离，一指不动，另一指移动(为了不干扰系统两指滚动，缩放等操作)
