### ISSUE TITLE
三指拖动有点问题

### ISSUE THREAD

**Issue by guo-jinbing** [zhaokeli/FastGestures#7]
系统：win11
1.三指拖动某个窗口并左右移动多次后，窗口一直往左边跑，因为触摸板上往左和往右移动相同距离时，屏幕上往左移动的多一些，感觉很难往右拖动。
2.微信截图时，如果中途打断，想继续拖动，好像很容易会变成双击保存。

**Comment by zhaokeli** [comment]
触发三指移动后， 是以中间手指移动距离为准，并且手指接触点并没有鼠标那么精准，移动速度过快，会生成大量无用的移动点，从而会产生飘的感觉。电脑卡时优为明显，

微信截图中途打断：具体怎么操作？   先截图，然后再三指拖动吗？

**Comment by guo-jinbing** [comment]
> 

电脑是刚刚买的1万多块的，应该不至于性能有问题。
微信截图的操作是，点击微信截图按钮，然后三指选中某个区域后放开三指，再继续从刚刚选中区域的右下角用三指扩大选中区域，有一定概率会直接确定截图而不是扩大区域。

**Comment by zhaokeli** [comment]
> 

向左偏移问题2.1.10已经解决，问题，暂无复现。

**Comment by guo-jinbing** [comment]
> > 
> 
> 向左偏移问题2.1.10已经解决，问题，暂无复现。

点赞！
