### ISSUE TITLE
三指和四指的问题

### ISSUE THREAD

**Issue by guo-jinbing** [zhaokeli/FastGestures#8]
win11下，三指快速多次单击会执行win+p，四指快速多次单击会截屏。在只开启三指拖动、关闭所有手指短按的前提下也会出现。

**Comment by zhaokeli** [comment]
![image](https://user-images.githubusercontent.com/2497841/165018506-94d9f86d-cfbe-4586-8f7d-7e853e3487ea.png)

此处配置截图看下。

**Comment by guo-jinbing** [comment]
![image](https://user-images.githubusercontent.com/29250730/165022451-a4096260-69ce-412d-92c1-a798c68d47b5.png)

**Comment by zhaokeli** [comment]
上面触发的截图 、win+p快捷键 是系统手势设置的吧？ 软件不会屏蔽系统手势，系统设置的有就还有。

**Comment by zhaokeli** [comment]
确实有这种情况。会在下个版本修正。感谢反馈。
