### ISSUE TITLE
启动时自动打开窗口的问题

### ISSUE THREAD

**Issue by georgel2020** [zhaokeli/FastGestures#9]
我没有使应用自动启动，而是使用了自己编写的一个应用延迟启动。但每次启动后都会弹出主窗口，能否有设置，在启动应用（FastGestures.exe）时先不显示程序窗口，自动隐藏到托盘？

**Comment by 735579768** [comment]
> 

C:\Program Files\FastGestures\FastGestures.exe --hidden=1
